import Header from '../components/Header';
import Footer from '../components/Footer';
import { colors, sectionStyle } from '../styles/shared';

export default function RefundPolicyPage() {
  const h2 = { fontSize: '22px', fontWeight: 700, color: colors.textPrimary, marginTop: '36px', marginBottom: '12px' };
  const p = { color: colors.textSecondary, fontSize: '15px', lineHeight: 1.8, marginBottom: '16px' };

  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #0a0a0f 0%, #1a1a2e 50%, #0a0a0f 100%)' }}>
      <Header />
      <div style={{ ...sectionStyle, paddingTop: '120px', maxWidth: '720px' }}>
        <h1 style={{ fontSize: '36px', fontWeight: 700, color: colors.textPrimary, marginBottom: '8px' }}>
          Refund Policy
        </h1>
        <p style={{ ...p, color: colors.textMuted, marginBottom: '36px' }}>Last updated: March 24, 2026</p>

        <h2 style={h2}>Free Trial</h2>
        <p style={p}>
          All new subscribers start with a 7-day free trial. During the trial period, you can use the full Service at
          no charge. If you cancel before the trial ends, you will not be charged. No refund is needed since no payment
          is collected during the trial.
        </p>

        <h2 style={h2}>Subscription Cancellation</h2>
        <p style={p}>
          You may cancel your subscription at any time from your Account page or through the Stripe billing portal.
          When you cancel, your subscription remains active until the end of the current billing period. No partial
          refunds are issued for unused time within a billing cycle.
        </p>

        <h2 style={h2}>Song Quality Issues</h2>
        <p style={p}>
          Since songs are generated by AI technology, results may vary. If you are unsatisfied with a generated song,
          you may create a new song request using a different story or style within your monthly limit of 10 songs.
          Song quality alone does not qualify for a refund, as AI generation is inherently variable.
        </p>

        <h2 style={h2}>Technical Failures</h2>
        <p style={p}>
          If a song fails to generate due to a technical error on our end, the failed request will not count toward
          your monthly limit. You can resubmit the request at no additional cost. If persistent technical issues prevent
          you from using the Service, contact us for a pro-rated refund for the affected period.
        </p>

        <h2 style={h2}>Requesting a Refund</h2>
        <p style={p}>
          To request a refund for eligible situations (billing errors, duplicate charges, or persistent technical
          failures), contact us at support@songforyou.app with your account email and a description of the issue. We
          will review requests within 5 business days. Approved refunds are processed through Stripe to your original
          payment method.
        </p>

        <h2 style={h2}>Chargebacks</h2>
        <p style={p}>
          We encourage you to contact us directly before initiating a chargeback with your bank or credit card company.
          We are committed to resolving billing disputes fairly and promptly.
        </p>

        <h2 style={h2}>Contact</h2>
        <p style={p}>
          For refund requests or billing questions, email us at support@songforyou.app.
        </p>
      </div>
      <Footer />
    </div>
  );
}
